[phases.setup]
nixPkgs = ["nodejs", "php", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "cd /app && ./start-no-db-fixed.sh"
