[phases.setup]
nixPkgs = ["nodejs", "php", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan view:cache",
    "php artisan route:cache"
]

[start]
cmd = "cd /app && ./simple-laravel-start.sh"
