[phases.setup]
nixPkgs = ["nodejs", "php", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build"
]

[start]
cmd = "cd /app && ./fix-start.sh"
