#!/bin/bash

# Set environment variables for Railway deployment
echo "🔧 Setting environment variables for Railway..."

# Create .env file with correct values
cat > /app/.env << EOF
APP_NAME="OmniChain"
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=https://web-production-8c4a.up.railway.app

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=pgsql
DB_HOST=\$RAILWAY_PRIVATE_DOMAIN
DB_PORT=5432
DB_DATABASE=\$POSTGRES_DB
DB_USERNAME=\$POSTGRES_USER
DB_PASSWORD=\$POSTGRES_PASSWORD

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=\$RAILWAY_PRIVATE_DOMAIN
REDIS_PASSWORD=\$REDIS_PASSWORD
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="OmniChain"

VITE_APP_NAME="OmniChain"
VITE_PUSHER_APP_KEY=""
VITE_PUSHER_HOST=""
VITE_PUSHER_PORT="443"
VITE_PUSHER_SCHEME="https"
VITE_PUSHER_APP_CLUSTER="mt1"

# External API Keys
OPENROUTE_API_KEY="eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImM4ZjI4MjJmYWU2MzRiYTZhMjk5NWM0YWI2MGJkMGQ2IiwiaCI6Im11cm11cjY0In0="
OPENWEATHER_API_KEY="7ba818bbe65339f2fc489561e114d7be"
EOF

echo "✅ Environment variables set successfully!"
